# Generated by Django 5.2.17 on 2026-09-25 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("actor_id", models.PositiveIntegerField(blank=True, null=True)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("object_ref", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(db_index=True, max_length=32)),
            ],
            options={
                "ordering": ["-at", "-pk"],
            },
        ),
    ]
