# Generated by Django 5.2.17 on 2026-09-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_engagement_tender_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("step", models.CharField(max_length=120)),
                ("due_on", models.DateField()),
                ("legal_latest", models.DateField(blank=True, null=True)),
                ("ambiguous", models.BooleanField(default=False)),
                ("source_section", models.CharField(blank=True, max_length=40)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deadlines",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ["due_on"],
            },
        ),
        migrations.CreateModel(
            name="UpcomingDeadline",
            fields=[],
            options={
                "verbose_name": "deadline in the next 14 days",
                "verbose_name_plural": "deadlines in the next 14 days",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("alerts.deadline",),
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("idempotency_key", models.CharField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("calendar", "calendar"),
                            ("T-7", "T-7"),
                            ("T-3", "T-3"),
                            ("T-1", "T-1"),
                        ],
                        max_length=16,
                    ),
                ),
                ("due_at", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=80)),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox",
                        to="alerts.deadline",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
    ]
