# Generated by Django 5.2.17 on 2026-09-24 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("jurisdiction", models.CharField(default="gr", max_length=8)),
                ("name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "jurisdiction", "tax_id"),
                        name="client_tax_id_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("tender_id", models.CharField(max_length=100)),
                ("tender_version", models.CharField(max_length=40)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[("dps", "dps"), ("open", "open")], max_length=32
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ADMITTED", "ADMITTED"),
                            ("APPLIED", "APPLIED"),
                            ("AWARDED", "AWARDED"),
                            ("CLOSED", "CLOSED"),
                            ("CONTRACTED", "CONTRACTED"),
                            ("NOT_AWARDED", "NOT_AWARDED"),
                            ("ONBOARDING", "ONBOARDING"),
                            ("PREPARING", "PREPARING"),
                            ("REGISTERED", "REGISTERED"),
                            ("REJECTED", "REJECTED"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("WITHDRAWN", "WITHDRAWN"),
                        ],
                        max_length=32,
                    ),
                ),
                ("admitted_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagements",
                        to="engagements.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("invitation_ref", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ABANDONED", "ABANDONED"),
                            ("AWARDED", "AWARDED"),
                            ("CHECKED", "CHECKED"),
                            ("CLIENT_SUBMITTED", "CLIENT_SUBMITTED"),
                            ("DRAFT", "DRAFT"),
                            ("NOT_AWARDED", "NOT_AWARDED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("offer_check", models.JSONField(blank=True, null=True)),
                ("gonogo_snapshot", models.JSONField(blank=True, null=True)),
                ("checklist_snapshot", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to="engagements.engagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Acknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "exclusion_grounds_reviewed",
                                "Exclusion Grounds Reviewed",
                            ),
                            ("fuel_risk", "Fuel Risk"),
                            ("cancellation_risk", "Cancellation Risk"),
                            ("gonogo_seen", "Gonogo Seen"),
                        ],
                        max_length=40,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField()),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("sector", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=100)),
                ("attributes", models.JSONField(default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="engagements.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True, default=1)),
                ("doc_type", models.CharField(max_length=64)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "manual_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SATISFIED", "SATISFIED"),
                            ("NOT_SATISFIED", "NOT_SATISFIED"),
                        ],
                        max_length=16,
                    ),
                ),
                ("applicable", models.BooleanField(default=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="engagements.client",
                    ),
                ),
                (
                    "seen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="engagements.resource",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "client", "tender_id"), name="engagement_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "ADMITTED",
                            "APPLIED",
                            "AWARDED",
                            "CLOSED",
                            "CONTRACTED",
                            "NOT_AWARDED",
                            "ONBOARDING",
                            "PREPARING",
                            "REGISTERED",
                            "REJECTED",
                            "SUBMITTED",
                            "WITHDRAWN",
                        ],
                    )
                ),
                name="engagement_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "engagement", "invitation_ref"), name="bid_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "ABANDONED",
                            "AWARDED",
                            "CHECKED",
                            "CLIENT_SUBMITTED",
                            "DRAFT",
                            "NOT_AWARDED",
                        ],
                    )
                ),
                name="bid_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("issued_on__isnull", True),
                    ("valid_until__gte", models.F("issued_on")),
                    _connector="OR",
                ),
                name="document_valid_after_issue",
            ),
        ),
    ]
