# Generated by Django 5.2.17 on 2026-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="tender_title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
