# Generated by Django 5.2.17 on 2026-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_engagement_tender_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="sector",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
