# Generated by Django 5.2.17 on 2026-09-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0003_engagement_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubject",
            fields=[],
            options={
                "verbose_name": "data subject",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("engagements.client",),
        ),
    ]
